version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: oee-data-collector-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: oee-data-collector
    ports:
      - "5432:5432"
    volumes:
      - meu_volume:/var/lib/postgresql/data

volumes:
  meu_volume: